version: "3.9"

services:
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"   # S3 API
      - "9001:9001"   # Web консоль
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minioadmin}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-minioadmin123}
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mlops-app
    depends_on:
      - minio
    ports:
      - "8000:8000"   # FastAPI
      - "50051:50051" # gRPC
    environment:
      # Настройки доступа к Minio для S3/DVC
      S3_ENDPOINT_URL: http://minio:9000
      S3_ACCESS_KEY: ${MINIO_ROOT_USER:-minioadmin}
      S3_SECRET_KEY: ${MINIO_ROOT_PASSWORD:-minioadmin123}
      S3_BUCKET_MODELS: mlops-hw1-models
      S3_BUCKET_DVC: mlops-hw1-dvc
      PYTHONUNBUFFERED: "1"
    volumes:
      # Чтобы DVC-конфиг и кэш жили вне контейнера
      - ./.dvc:/app/.dvc
      - ./data:/app/data

volumes:
  minio_data: