# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import mlops_hw1_pb2 as mlops__hw1__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in mlops_hw1_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MLServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetStatus = channel.unary_unary(
                '/mlops_hw1.MLService/GetStatus',
                request_serializer=mlops__hw1__pb2.Empty.SerializeToString,
                response_deserializer=mlops__hw1__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.ListModels = channel.unary_unary(
                '/mlops_hw1.MLService/ListModels',
                request_serializer=mlops__hw1__pb2.Empty.SerializeToString,
                response_deserializer=mlops__hw1__pb2.ListModelsResponse.FromString,
                _registered_method=True)
        self.Train = channel.unary_unary(
                '/mlops_hw1.MLService/Train',
                request_serializer=mlops__hw1__pb2.TrainRequest.SerializeToString,
                response_deserializer=mlops__hw1__pb2.TrainResponse.FromString,
                _registered_method=True)
        self.Predict = channel.unary_unary(
                '/mlops_hw1.MLService/Predict',
                request_serializer=mlops__hw1__pb2.PredictRequest.SerializeToString,
                response_deserializer=mlops__hw1__pb2.PredictResponse.FromString,
                _registered_method=True)
        self.DeleteModel = channel.unary_unary(
                '/mlops_hw1.MLService/DeleteModel',
                request_serializer=mlops__hw1__pb2.DeleteRequest.SerializeToString,
                response_deserializer=mlops__hw1__pb2.DeleteResponse.FromString,
                _registered_method=True)
        self.Retrain = channel.unary_unary(
                '/mlops_hw1.MLService/Retrain',
                request_serializer=mlops__hw1__pb2.RetrainRequest.SerializeToString,
                response_deserializer=mlops__hw1__pb2.RetrainResponse.FromString,
                _registered_method=True)


class MLServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListModels(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Train(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Predict(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Retrain(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MLServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStatus,
                    request_deserializer=mlops__hw1__pb2.Empty.FromString,
                    response_serializer=mlops__hw1__pb2.StatusResponse.SerializeToString,
            ),
            'ListModels': grpc.unary_unary_rpc_method_handler(
                    servicer.ListModels,
                    request_deserializer=mlops__hw1__pb2.Empty.FromString,
                    response_serializer=mlops__hw1__pb2.ListModelsResponse.SerializeToString,
            ),
            'Train': grpc.unary_unary_rpc_method_handler(
                    servicer.Train,
                    request_deserializer=mlops__hw1__pb2.TrainRequest.FromString,
                    response_serializer=mlops__hw1__pb2.TrainResponse.SerializeToString,
            ),
            'Predict': grpc.unary_unary_rpc_method_handler(
                    servicer.Predict,
                    request_deserializer=mlops__hw1__pb2.PredictRequest.FromString,
                    response_serializer=mlops__hw1__pb2.PredictResponse.SerializeToString,
            ),
            'DeleteModel': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteModel,
                    request_deserializer=mlops__hw1__pb2.DeleteRequest.FromString,
                    response_serializer=mlops__hw1__pb2.DeleteResponse.SerializeToString,
            ),
            'Retrain': grpc.unary_unary_rpc_method_handler(
                    servicer.Retrain,
                    request_deserializer=mlops__hw1__pb2.RetrainRequest.FromString,
                    response_serializer=mlops__hw1__pb2.RetrainResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mlops_hw1.MLService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('mlops_hw1.MLService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MLService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mlops_hw1.MLService/GetStatus',
            mlops__hw1__pb2.Empty.SerializeToString,
            mlops__hw1__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListModels(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mlops_hw1.MLService/ListModels',
            mlops__hw1__pb2.Empty.SerializeToString,
            mlops__hw1__pb2.ListModelsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Train(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mlops_hw1.MLService/Train',
            mlops__hw1__pb2.TrainRequest.SerializeToString,
            mlops__hw1__pb2.TrainResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Predict(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mlops_hw1.MLService/Predict',
            mlops__hw1__pb2.PredictRequest.SerializeToString,
            mlops__hw1__pb2.PredictResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mlops_hw1.MLService/DeleteModel',
            mlops__hw1__pb2.DeleteRequest.SerializeToString,
            mlops__hw1__pb2.DeleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Retrain(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mlops_hw1.MLService/Retrain',
            mlops__hw1__pb2.RetrainRequest.SerializeToString,
            mlops__hw1__pb2.RetrainResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
